"use client";

import Link from "next/link";
import { useActionState } from "react";
import { login, signup, type FormState } from "@/lib/actions";
import { SubmitButton } from "@/components/SubmitButton";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const [state, action] = useActionState<FormState, FormData>(mode === "login" ? login : signup, undefined);
  return (
    <form action={action} className="card space-y-4 p-6">
      {mode === "signup" && (
        <div>
          <label className="label" htmlFor="name">Your name</label>
          <input className="input" id="name" name="name" autoComplete="name" required />
        </div>
      )}
      <div>
        <label className="label" htmlFor="email">Email</label>
        <input className="input" id="email" name="email" type="email" autoComplete="email" required />
      </div>
      <div>
        <label className="label" htmlFor="password">Password</label>
        <input
          className="input"
          id="password"
          name="password"
          type="password"
          minLength={8}
          autoComplete={mode === "login" ? "current-password" : "new-password"}
          required
        />
      </div>
      {mode === "signup" && (
        <label className="flex items-start gap-2 text-sm text-ink-2">
          <input type="checkbox" name="consent" className="mt-1" required />
          <span>
            I agree to the <Link href="/privacy" className="text-accent underline">privacy policy</Link> and understand
            MEpa&apos;s advice is generated by AI.
          </span>
        </label>
      )}
      {state?.error && <p className="text-sm text-bad">{state.error}</p>}
      <SubmitButton className="w-full">{mode === "login" ? "Log in" : "Create account"}</SubmitButton>
      <p className="text-center text-sm text-ink-3">
        {mode === "login" ? (
          <>New here? <Link href="/signup" className="text-accent">Create an account</Link></>
        ) : (
          <>Already have an account? <Link href="/login" className="text-accent">Log in</Link></>
        )}
      </p>
    </form>
  );
}
