import { Logo } from "@/components/Logo";

export const metadata = { title: "Privacy · MEpa" };

export default function Privacy() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      <Logo />
      <h1 className="mt-8 text-2xl font-bold">Privacy policy</h1>
      <p className="mt-2 text-sm text-ink-3">Draft. Have this reviewed by a lawyer before launch.</p>
      <div className="mt-6 space-y-4 text-sm leading-relaxed text-ink-2">
        <p><strong className="text-ink">What we collect.</strong> Your account details (name, email), the profile you fill in, and, for each social account you connect, your public profile, post list and the performance and audience statistics the platform shares with us. We store access tokens encrypted.</p>
        <p><strong className="text-ink">Why.</strong> Only to give you analytics, AI advice, reports, content plans and your media kit. We never post, comment or message on your behalf, and we never sell your data.</p>
        <p><strong className="text-ink">AI processing.</strong> To answer your questions, relevant parts of your data are sent to our AI provider (Anthropic) under a data processing agreement. MEpa&apos;s advice is generated by AI and can be wrong; it is not legal or financial advice.</p>
        <p><strong className="text-ink">Where.</strong> Data is hosted in the EU.</p>
        <p><strong className="text-ink">Your control.</strong> Disconnecting an account deletes its synced data. Deleting your MEpa account (Profile page) permanently deletes everything we hold about you. You can also revoke access from each platform&apos;s settings at any time.</p>
        <p><strong className="text-ink">Contact.</strong> privacy@your-domain.example</p>
      </div>
    </div>
  );
}
